# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Download wrappers
        uses: actions/download-artifact@v1
        with:
          name: lib-wrapper
          path: src/FMU4FOAM/resources
    
      - name: Build distribution artifacts
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_CASEFOAM_API_TOKEN }}
        run: |
          ls dist
          twine upload dist/*
